### ISSUE TITLE
iPhone 7 and iPhone 7 plus

### ISSUE THREAD

**Issue by lloydpowell88** [litmus/litmus-mobile-samples#2]
Hi,

Are there any plans to add the new iPhone 7 and 7 plus devices?

Thanks

**Comment by edgiardina** [comment]
Hi Lloyd,

I'll get this request routed to the right people and see if we can get those images up in this repo ASAP. Thanks for bringing it to our attention!

- Ed

**Comment by edgiardina** [comment]
@lloydpowell88 the required files have been provided. Thanks again. 🎩 to @adnan959

**Comment by lloydpowell88** [comment]
Fantastic, thank you to you both!
