### ISSUE TITLE
android device skins

### ISSUE THREAD

**Issue by lloydpowell88** [litmus/litmus-mobile-samples#4]
Hi guys, me again (sorry to be a pain),

I was wondering if there were any intentions of adding any of the newer android device skins, do we know what actual devices litmus test for the android based previews? I think the latest in this library is the nexus.

Thanks again, the speed of adding the iPhone skins was fantastic!

**Comment by defeated** [comment]
@lloydpowell88 Hi Lloyd, I've got a ticket in for releasing our latest Android assets:

  * 4.4
  * 5.1
  * 6.0

Stay tuned!

**Comment by alantippins** [comment]
Hey @lloydpowell88 I've just updated the repo to match what we use in the litmus app for 4.4, 5.1 and 6.0 here: https://github.com/litmus/litmus-mobile-samples/commit/80851d105a8acb4bb9ceaa38e66204dd62ea4647.

**Comment by lloydpowell88** [comment]
@alantippins fantastic! Thank you!
