### ISSUE TITLE
Update mobile samples

### ISSUE THREAD

**Issue by defeated** [litmus/litmus-mobile-samples#5]
> Make sure to include newest iOS and Android client chromes

refs litmus/litmus.net#3184

/cc @drostocil

**Comment by defeated** [comment]
@alantippins can this be worked into support friday for your design folks?

**Comment by alantippins** [comment]
:+1: @adnan959 Did we already update the ios sample or was that just for gmail for ios?

Edit: Setup as a design-sf task: https://github.com/litmus/litmus/issues/8167
