### ISSUE TITLE
iPhone 8 and iPhone 8 Plus skins

### ISSUE THREAD

**Issue by lloydpowell88** [litmus/litmus-mobile-samples#6]
Hi,

Do you have skins for the iPhone 8 and iPhone 8 Plus devices that have recently been added? Or would it be OK to use the iPhone 7 skins?

Thanks again,

Lloyd

**Comment by adnan959** [comment]
Hey Lloyd,

We've just added the iPhone 8 skins via https://github.com/litmus/litmus-mobile-samples/commit/f5f7d841f5f5a47308c80a8635cac17ccd79304d. 

If you have any additional questions, feel free to let me know. 

Adnan
