### ISSUE TITLE
iPhone X, iPhone SE and Samsung Skins

### ISSUE THREAD

**Issue by lloydpowell88** [litmus/litmus-mobile-samples#7]
Hi guys,

Will the iPhone 8 skin suffice for the iPhone X email client preview? If not, are there any plans to add it in to here?

Thanks again :-)

**Comment by lloydpowell88** [comment]
Also, I've notice there is now the iPhone SE too, along with the Samsung Android. Should I just use the iPhone 5s for the SE and the previous android device for the Samsung or is there specific skins for those too?

**Comment by edgiardina** [comment]
Hey Lloyd,

Sorry no one has gotten back to you. Let me see if I can track down someone to create the art for it. The Samsung and iPhone SE vs 5S are a design decision on our team, we usually try to represent the device and not re-use to avoid customer confusion.

Thanks,

- Ed

**Comment by edgiardina** [comment]
@adnan959 looks like you last helped us with this. I'm going to create a JIRA in our board. Can you just update this git issue when the work has been completed or handed off to someone else? Thank you!

**Comment by adnan959** [comment]
Hey @lloydpowell88, 

I've just added the missing device samples, while we're re-using the same skins for the iPhoneSE and Samsung Android, the iPhone X one is significantly different (https://github.com/litmus/litmus-mobile-samples/commit/cedd5d3d2aa81511fb317ea7aa0480223ea6ffa7).

I hope this helps, if you have any additional questions -- just let us know! 

Thanks,
Adnan
